/*
combined tb of main control unit and ALU_control
*/
`timescale 1ns/1ps

module Control_System_tb;

reg  [6:0] opcode; //come from instruction
reg  [2:0] funct3; //come from instruction
reg  [6:0] funct7; //come from instruction

wire       RegWrite; //come from main control unit
wire       MemRead;  //come from main control unit
wire       MemWrite; //come from main control unit

wire       Branch;   //come from main control unit
wire       Jump;     //come from main control unit
wire       JALR;     //come from main control unit

wire [1:0] SrcASel;  //come from main control unit
wire       ALUSrc;    //come from main control unit

wire [1:0] ResultSrc; //come from main control unit
wire [2:0] ImmSrc;    //come from main control unit

wire [1:0] ALUOp; //come from main control unit
wire [3:0] ALU_Control;  //come from ALUcontrol


// =========================================
// MAIN CONTROL UNIT
// =========================================

Control_Unit main_control (

    .opcode(opcode), //come from instruction

    .RegWrite(RegWrite),
    .MemRead(MemRead),
    .MemWrite(MemWrite),

    .Branch(Branch),
    .Jump(Jump),
    .JALR(JALR),

    .SrcASel(SrcASel),
    .ALUSrc(ALUSrc),

    .ResultSrc(ResultSrc),
    .ImmSrc(ImmSrc),

    .ALUOp(ALUOp) //general instruction category for the ALU.
                  //It is generated by the Main Control Unit.

);


// =========================================
// ALU CONTROL
// =========================================

ALU_Control alu_control (

    .ALUOp(ALUOp), //come from control unit

    .funct3(funct3), //come from instruction
    .funct7(funct7), //come from instruction

    .ALU_Control(ALU_Control) //exact operation code sent to your ALU.

);


// =========================================
// TESTING
// =========================================

initial begin

    $monitor(
        "opcode=%b funct3=%b funct7=%b | ALUOp=%b ALU_Control=%b | RegWrite=%b MemRead=%b MemWrite=%b Branch=%b Jump=%b JALR=%b SrcASel=%b ALUSrc=%b ResultSrc=%b ImmSrc=%b",
        opcode,
        funct3,
        funct7,
        ALUOp,
        ALU_Control,
        RegWrite,
        MemRead,
        MemWrite,
        Branch,
        Jump,
        JALR,
        SrcASel,
        ALUSrc,
        ResultSrc,
        ImmSrc
    );


    // =====================================
    // R-TYPE ADD
    // =====================================

    opcode = 7'b0110011;
    funct3 = 3'b000;
    funct7 = 7'b0000000;
    #10;


    // =====================================
    // R-TYPE SUB
    // =====================================

    opcode = 7'b0110011;
    funct3 = 3'b000;
    funct7 = 7'b0100000;
    #10;


    // =====================================
    // R-TYPE AND
    // =====================================

    opcode = 7'b0110011;
    funct3 = 3'b111;
    funct7 = 7'b0000000;
    #10;


    // =====================================
    // R-TYPE OR
    // =====================================

    opcode = 7'b0110011;
    funct3 = 3'b110;
    funct7 = 7'b0000000;
    #10;


    // =====================================
    // ADDI
    // =====================================

    opcode = 7'b0010011;
    funct3 = 3'b000;
    funct7 = 7'b0000000;
    #10;


    // =====================================
    // SRAI
    // =====================================

    opcode = 7'b0010011;
    funct3 = 3'b101;
    funct7 = 7'b0100000;
    #10;


    // =====================================
    // LW
    // =====================================

    opcode = 7'b0000011;
    funct3 = 3'b010;
    funct7 = 7'b0000000;
    #10;


    // =====================================
    // SW
    // =====================================

    opcode = 7'b0100011;
    funct3 = 3'b010;
    funct7 = 7'b0000000;
    #10;


    // =====================================
    // BEQ
    // =====================================

    opcode = 7'b1100011;
    funct3 = 3'b000;
    funct7 = 7'b0000000;
    #10;


    // =====================================
    // BLTU
    // =====================================

    opcode = 7'b1100011;
    funct3 = 3'b110;
    funct7 = 7'b0000000;
    #10;


    // =====================================
    // JAL
    // =====================================

    opcode = 7'b1101111;
    funct3 = 3'b000;
    funct7 = 7'b0000000;
    #10;


    // =====================================
    // JALR
    // =====================================

    opcode = 7'b1100111;
    funct3 = 3'b000;
    funct7 = 7'b0000000;
    #10;


    // =====================================
    // LUI
    // =====================================

    opcode = 7'b0110111;
    funct3 = 3'b000;
    funct7 = 7'b0000000;
    #10;


    // =====================================
    // AUIPC
    // =====================================

    opcode = 7'b0010111;
    funct3 = 3'b000;
    funct7 = 7'b0000000;
    #10;


    $stop;

end

endmodule